export const SEEDED_COMPETITORS = [
  {
    name: "Beacon Hospice, An Amedisys Company",
    aliases: ["Beacon Hospice", "Amedisys Hospice", "Beacon Hospice An Amedisys Company"],
    parent_company: "Amedisys",
    provider_type: "hospice",
    website_url: "https://www.amedisys.com",
    known_counties: ["Androscoggin", "Penobscot", "Cumberland"],
  },
  {
    name: "Gentiva",
    aliases: ["Gentiva Hospice", "Gentiva Health Services"],
    parent_company: "Gentiva Health Services",
    provider_type: "hospice",
    website_url: "https://www.gentiva.com",
    known_counties: ["Penobscot"],
  },
  {
    name: "Kindred Hospice",
    aliases: ["Kindred at Home", "Kindred Hospice"],
    parent_company: "Gentiva Health Services",
    provider_type: "hospice",
    website_url: "https://www.gentiva.com",
    known_counties: ["Cumberland"],
  },
  {
    name: "Northern Light Home Care and Hospice",
    aliases: ["Northern Light Home Care & Hospice", "NLHCH", "Northern Light"],
    parent_company: "Northern Light Health",
    provider_type: "both",
    website_url: "https://northernlighthealth.org/Locations/Northern-Light-Home-Care-Hospice",
    known_counties: ["Cumberland", "Penobscot", "Kennebec"],
  },
  {
    name: "MaineHealth Care at Home",
    aliases: ["MaineHealth Care At Home", "MH Care at Home"],
    parent_company: "MaineHealth",
    provider_type: "both",
    website_url: "https://mainehealth.org/care-at-home",
    known_counties: ["York", "Cumberland"],
  },
  {
    name: "CHANS Home Health and Hospice",
    aliases: ["CHANS Home Health Care", "Chans Home Health & Hospice", "CHANS"],
    parent_company: "MaineHealth",
    provider_type: "both",
    website_url: "https://mainehealth.org/chans",
    known_counties: ["Cumberland"],
  },
  {
    name: "MaineGeneral Community Care",
    aliases: ["Mainegeneral Community Care", "MaineGeneral"],
    parent_company: "MaineGeneral Health",
    provider_type: "both",
    website_url: "https://www.mainegeneral.org/community-care",
    known_counties: ["Kennebec"],
  },
  {
    name: "Community Health and Counseling Services",
    aliases: ["Community Health & Counseling Services", "CHCS"],
    parent_company: null,
    provider_type: "both",
    website_url: "https://www.chcs-me.org",
    known_counties: ["Penobscot"],
  },
  {
    name: "St. Joseph Hospice",
    aliases: ["St Joseph Hospice", "St Joseph Homecare", "Saint Joseph Hospice"],
    parent_company: "Northern Light Health",
    provider_type: "both",
    website_url: "https://northernlighthealth.org/Locations/Northern-Light-St-Joseph-Hospital",
    known_counties: ["Penobscot"],
  },
  {
    name: "Bristol Hospice",
    aliases: ["Bristol Hospice Maine"],
    parent_company: "Bristol Hospice",
    provider_type: "hospice",
    website_url: "https://bristolhospice.com",
    known_counties: [],
  },
  {
    name: "Compassus Hospice",
    aliases: ["Compassus Greater Maine", "Compassus"],
    parent_company: "Compassus",
    provider_type: "hospice",
    website_url: "https://www.compassus.com",
    known_counties: ["Cumberland"],
  },
  {
    name: "Constellation Hospice",
    aliases: ["Constellation Home Care Me Llc", "Constellation Home Care"],
    parent_company: "Constellation Health Services",
    provider_type: "both",
    website_url: "https://www.constellationhealthservices.com",
    known_counties: ["Androscoggin"],
  },
  {
    name: "Affinity Care of Maine",
    aliases: ["Affinity Care Of Maine Llc", "Affinity Care"],
    parent_company: null,
    provider_type: "hospice",
    website_url: null,
    known_counties: ["Cumberland"],
  },
  {
    name: "York Hospital Hospice and Palliative Care",
    aliases: ["York Hospital Home Care", "York Hospital Hospice"],
    parent_company: "York Hospital",
    provider_type: "both",
    website_url: "https://yorkhospital.com",
    known_counties: ["York"],
  },
  {
    name: "Miles and St. Andrews Home Health and Hospice",
    aliases: ["Miles Memorial Home Health", "Miles St Andrews"],
    parent_company: "MaineHealth",
    provider_type: "both",
    website_url: "https://mainehealth.org/miles-and-st-andrews",
    known_counties: ["Lincoln", "Knox"],
  },
  {
    name: "VNA Home Health and Hospice",
    aliases: ["VNA Hospice of Southern Maine", "Hospice of Southern Maine", "VNA"],
    parent_company: null,
    provider_type: "both",
    website_url: "https://www.vnacarenetwork.org",
    known_counties: ["Cumberland", "York"],
  },
  {
    name: "Hospice of Aroostook",
    aliases: ["Aroostook Hospice"],
    parent_company: null,
    provider_type: "hospice",
    website_url: "https://www.aroostookhospice.org",
    known_counties: ["Aroostook"],
  },
];

export const CMS_SEARCH_TERMS = {
  hospice: [
    "hospice provider data",
    "hospice care provider data",
    "hospice CAHPS provider data",
    "hospice state data",
    "hospice zip data",
  ],
  homehealth: [
    "home health care agencies",
    "home health provider data",
    "home health quality data",
    "HHCAHPS provider data",
    "home health state data",
  ],
};
